import { AnimatePresence, motion, useScroll, useTransform } from "framer-motion";
import { ArrowRight, Check, ChevronLeft, ChevronRight, Mail, MapPin, Menu, Phone, Star, X } from "lucide-react";
import { Link, useLocation } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { useServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { awards, blogPosts, contact, externalLinks, images, logoImage, logoText, nav, portfolioItems, services, testimonials } from "@/lib/site-data";
import { submitContact } from "@/lib/contact.functions";
import { Button } from "@/components/ui/button";

export function AnimatedLogo({ compact = false }: { compact?: boolean }) {
  return <Link to="/" className="group inline-flex items-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><img src={logoImage} alt="Creative Granite & Design" className={compact ? "h-10 w-auto object-contain transition-opacity group-hover:opacity-80 md:h-12" : "h-14 w-auto object-contain transition-opacity group-hover:opacity-80 md:h-16"} /></Link>;
}

export function Preloader() {
  const [done, setDone] = useState(false);
  const [progress, setProgress] = useState(0);
  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) { setDone(true); return; }
    let value = 0;
    const timer = window.setInterval(() => { value += Math.ceil(Math.random() * 9); setProgress(Math.min(value, 100)); if (value >= 100) { window.clearInterval(timer); window.setTimeout(() => setDone(true), 450); } }, 70);
    return () => window.clearInterval(timer);
  }, []);
    return <AnimatePresence>{!done && <motion.div className="fixed inset-0 z-[100] flex flex-col items-center justify-center overflow-hidden bg-obsidian text-ivory" exit={{ y: "-100%" }} transition={{ duration: 1, ease: [0.77, 0, 0.18, 1] }}><div className="absolute inset-0 marble-texture opacity-25" /><motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} className="relative text-center"><img src={logoImage} alt="Creative Granite & Design" className="mx-auto mb-7 h-20 w-auto object-contain" /><p className="text-xs uppercase tracking-[0.34em] text-ivory/70">{logoText}</p><div className="mt-10 h-px w-72 bg-ivory/15"><motion.div className="h-px bg-bronze" style={{ width: `${progress}%` }} /></div><p className="mt-5 font-display text-5xl text-ivory">{progress}</p></motion.div></motion.div>}</AnimatePresence>;
}

export function SmoothScrollProvider({ children }: { children: React.ReactNode }) {
  useEffect(() => { let lenis: { raf: (time: number) => void; destroy: () => void } | undefined; let frame = 0; import("lenis").then(({ default: Lenis }) => { if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return; lenis = new Lenis({ lerp: 0.08, wheelMultiplier: 0.85 }); const raf = (time: number) => { lenis?.raf(time); frame = requestAnimationFrame(raf); }; frame = requestAnimationFrame(raf); }); return () => { cancelAnimationFrame(frame); lenis?.destroy(); }; }, []);
  const { scrollYProgress } = useScroll();
  return <><motion.div className="fixed left-0 top-0 z-[90] h-0.5 origin-left bg-bronze" style={{ scaleX: scrollYProgress }} />{children}</>;
}

export function PageTransitionWrapper({ children }: { children: React.ReactNode }) {
  const location = useLocation();
  return <AnimatePresence mode="wait"><motion.main key={location.pathname} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -18 }} transition={{ duration: .55, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.main></AnimatePresence>;
}

export function Header() {
  const [open, setOpen] = useState(false);
  useEffect(() => { const onKey = (e: KeyboardEvent) => e.key === "Escape" && setOpen(false); window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-ivory/10 bg-obsidian/55 px-5 py-4 text-ivory backdrop-blur-xl md:px-9"><div className="mx-auto flex max-w-7xl items-center justify-between"><AnimatedLogo compact /><nav className="hidden items-center gap-7 text-[0.68rem] uppercase tracking-[0.22em] lg:flex">{nav.map((item) => <Link key={item.to} to={item.to as never} className="nav-underline text-ivory/78 transition-colors hover:text-bronze">{item.label}</Link>)}</nav><div className="flex items-center gap-3"><Button variant="bronze" size="sm" asChild><a href={externalLinks.estimator} target="_blank" rel="noreferrer">Get Estimate</a></Button><button onClick={() => setOpen(true)} aria-label="Open menu" className="grid size-10 place-items-center border border-ivory/15 text-ivory transition hover:border-bronze hover:text-bronze"><Menu size={18} /></button></div></div><FullScreenMenu open={open} onClose={() => setOpen(false)} /></header>;
}

export function FullScreenMenu({ open, onClose }: { open: boolean; onClose: () => void }) {
  return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-[80] bg-obsidian text-ivory" initial={{ clipPath: "inset(0 0 100% 0)" }} animate={{ clipPath: "inset(0 0 0% 0)" }} exit={{ clipPath: "inset(0 0 100% 0)" }} transition={{ duration: .75, ease: [0.77, 0, 0.18, 1] }}><div className="absolute inset-0 marble-texture opacity-20" /><div className="relative flex min-h-screen flex-col p-6 md:p-10"><div className="flex items-center justify-between"><AnimatedLogo /><button onClick={onClose} aria-label="Close menu" className="grid size-12 place-items-center border border-ivory/15 transition hover:border-bronze hover:text-bronze"><X /></button></div><div className="grid flex-1 items-end gap-10 py-12 md:grid-cols-[1fr_.7fr]"><nav className="space-y-4">{nav.map((item, index) => <motion.div key={item.to} initial={{ y: 28, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: .08 * index }}><Link to={item.to as never} onClick={onClose} className="font-display text-5xl leading-none text-ivory transition hover:text-bronze md:text-7xl">{item.label}</Link></motion.div>)}</nav><motion.aside initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .35 }} className="space-y-6 border-t border-ivory/15 pt-8 text-sm text-ivory/72 md:border-l md:border-t-0 md:pl-10 md:pt-0"><Button variant="bronze" asChild><a href={externalLinks.estimator} target="_blank" rel="noreferrer">Get a Free Estimate</a></Button><p><Phone className="mr-2 inline size-4 text-bronze" />{contact.phone}</p><p><Mail className="mr-2 inline size-4 text-bronze" />{contact.email}</p><p><MapPin className="mr-2 inline size-4 text-bronze" />{contact.address}</p><a className="nav-underline text-bronze" href={externalLinks.instagram} target="_blank" rel="noreferrer">Instagram</a></motion.aside></div></div></motion.div>}</AnimatePresence>;
}

export function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="mb-5 text-xs font-semibold uppercase tracking-[0.3em] text-bronze">{children}</p>; }
export function SplitTextReveal({ text, className = "" }: { text: string; className?: string }) { return <motion.h2 initial="hidden" whileInView="show" viewport={{ once: true, margin: "-80px" }} variants={{ hidden: {}, show: { transition: { staggerChildren: .08 } } }} className={`font-display leading-[0.95] tracking-normal ${className}`}>{text.split(" ").map((word, i) => <motion.span key={`${word}-${i}`} className="mr-3 inline-block overflow-hidden" variants={{ hidden: { y: "105%", opacity: 0 }, show: { y: 0, opacity: 1 } }}>{word}</motion.span>)}</motion.h2>; }
export function ImageReveal({ src, alt, className = "" }: { src: string; alt: string; className?: string }) { return <motion.div initial={{ clipPath: "inset(0 100% 0 0)" }} whileInView={{ clipPath: "inset(0 0% 0 0)" }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: .9, ease: [0.77, 0, 0.18, 1] }} className={`overflow-hidden bg-muted ${className}`}><motion.img src={src} alt={alt} loading="lazy" className="h-full w-full object-cover" initial={{ scale: 1.12 }} whileInView={{ scale: 1 }} transition={{ duration: 1.2, ease: "easeOut" }} /></motion.div>; }

export function HeroSlider() {
  const slides = ["Luxury Marble & Granite Countertops", "Countertops, Vanities, Fireplaces & More", "Quartz, Quartzite & Solid Surface Countertops", "Finest Quality & Service"];
  const [active, setActive] = useState(0);
  const { scrollY } = useScroll();
  const y = useTransform(scrollY, [0, 800], [0, 140]);
  useEffect(() => { const id = window.setInterval(() => setActive((v) => (v + 1) % slides.length), 4300); return () => window.clearInterval(id); }, [slides.length]);
  return <section className="relative min-h-screen overflow-hidden bg-obsidian text-ivory"><motion.img style={{ y }} initial={{ scale: 1.12 }} animate={{ scale: 1 }} transition={{ duration: 1.8 }} src={active % 2 ? images.hero2 : images.hero} alt="Luxury Creative Granite countertop installation" className="absolute inset-0 h-[115%] w-full object-cover opacity-72" /><div className="absolute inset-0 bg-gradient-to-b from-obsidian/70 via-obsidian/35 to-obsidian" /><div className="relative z-10 flex min-h-screen items-end px-5 pb-20 pt-32 md:px-10 md:pb-28"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-[1fr_.45fr] md:items-end"><div><SectionLabel>Welcome To Creative Granite & Design</SectionLabel><AnimatePresence mode="wait"><motion.h1 key={slides[active]} initial={{ y: 40, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: -30, opacity: 0 }} transition={{ duration: .65 }} className="max-w-5xl font-display text-6xl leading-[0.9] text-ivory md:text-8xl lg:text-9xl">{slides[active]}</motion.h1></AnimatePresence></div><motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .8 }} className="space-y-6 text-ivory/78"><p className="text-lg leading-relaxed">#1 Source For Natural Stone Countertops in Salt Lake City, Utah, serving homeowners, builders, architects, and designers across Utah, Idaho, and Wyoming.</p><div className="flex flex-wrap gap-3"><Button variant="bronze" asChild><Link to="/contact">Visit Showroom</Link></Button><Button variant="outlineLuxury" asChild><a href={externalLinks.estimator} target="_blank" rel="noreferrer">Get a Free Quote</a></Button></div></motion.div></div></div></section>;
}

export function LuxuryButton({ children, href }: { children: React.ReactNode; href: string }) { const external = href.startsWith("http"); return <Button variant="bronze" asChild>{external ? <a href={href} target="_blank" rel="noreferrer">{children}</a> : <Link to={href as never}>{children}</Link>}</Button>; }
export function ServiceCard({ service, index }: { service: typeof services[number]; index: number }) { return <motion.article initial={{ y: 34, opacity: 0 }} whileInView={{ y: 0, opacity: 1 }} viewport={{ once: true }} transition={{ delay: index * .04 }} className="group grid gap-6 border-t border-border py-8 md:grid-cols-[.18fr_.45fr_.37fr] md:items-center"><span className="font-display text-4xl text-bronze/70">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-display text-4xl text-foreground md:text-5xl">{service.title}</h3><p className="mt-4 max-w-xl text-muted-foreground">{service.copy}</p><Link to="/services/$slug" params={{ slug: service.slug }} className="nav-underline mt-5 inline-flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-bronze">Read More <ArrowRight size={15} /></Link></div><div className="h-64 overflow-hidden"><img src={service.image} alt={`${service.title} by Creative Granite & Design`} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div></motion.article>; }

export function PortfolioGrid({ category }: { category?: string }) {
  const [filter, setFilter] = useState(category ?? "All"); const [selected, setSelected] = useState<typeof portfolioItems[number] | null>(null); const categories = ["All", "Kitchens", "Vanities", "Showers", "Fireplaces", "Parade of Homes", "Videos"]; const items = portfolioItems.filter((item) => filter === "All" || item.category === filter);
  return <section><div className="mb-9 flex flex-wrap gap-2">{categories.map((cat) => <button key={cat} onClick={() => setFilter(cat)} className={`border px-4 py-2 text-xs uppercase tracking-[0.2em] transition ${filter === cat ? "border-bronze bg-bronze text-bronze-foreground" : "border-border text-muted-foreground hover:border-bronze hover:text-bronze"}`}>{cat}</button>)}</div><motion.div layout className="grid gap-4 md:grid-cols-3">{items.map((item) => <motion.button layout key={item.id} onClick={() => setSelected(item)} className="group relative min-h-[360px] overflow-hidden text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><img src={item.image} alt={`${item.title} ${item.category}`} loading="lazy" className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-obsidian/85 to-transparent opacity-85" /><div className="absolute bottom-0 p-6 text-ivory"><p className="text-xs uppercase tracking-[0.28em] text-bronze">{item.category}</p><h3 className="mt-2 font-display text-4xl">{item.title}</h3><p className="text-sm text-ivory/65">{item.tone}</p></div></motion.button>)}</motion.div><PortfolioLightbox item={selected} onClose={() => setSelected(null)} /></section>;
}
export function PortfolioLightbox({ item, onClose }: { item: typeof portfolioItems[number] | null; onClose: () => void }) { return <AnimatePresence>{item && <motion.div className="fixed inset-0 z-[95] grid place-items-center bg-obsidian/92 p-5" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}><button aria-label="Close gallery" className="absolute right-5 top-5 text-ivory"><X /></button><motion.figure onClick={(e) => e.stopPropagation()} initial={{ scale: .96 }} animate={{ scale: 1 }} className="max-w-5xl"><img src={item.image} alt={item.title} className="max-h-[78vh] w-full object-contain" /><figcaption className="mt-4 text-ivory"><span className="text-bronze">{item.category}</span> — {item.title}</figcaption></motion.figure></motion.div>}</AnimatePresence>; }

export function HorizontalProjectSlider() { const [i, setI] = useState(0); const item = portfolioItems[i]; return <div className="overflow-hidden"><div className="mb-6 flex justify-end gap-2"><button aria-label="Previous project" onClick={() => setI((i - 1 + portfolioItems.length) % portfolioItems.length)} className="grid size-11 place-items-center border border-border hover:border-bronze"><ChevronLeft /></button><button aria-label="Next project" onClick={() => setI((i + 1) % portfolioItems.length)} className="grid size-11 place-items-center border border-border hover:border-bronze"><ChevronRight /></button></div><AnimatePresence mode="wait"><motion.div key={item.id} initial={{ x: 80, opacity: 0 }} animate={{ x: 0, opacity: 1 }} exit={{ x: -80, opacity: 0 }} className="grid gap-6 md:grid-cols-[.6fr_.4fr]"><ImageReveal src={item.image} alt={item.title} className="h-[560px]" /><div className="self-end"><SectionLabel>{item.category}</SectionLabel><h3 className="font-display text-6xl">{item.title}</h3><p className="mt-5 text-muted-foreground">{item.tone}</p></div></motion.div></AnimatePresence></div>; }
export function TimelineAwards() { return <div className="no-scrollbar flex gap-4 overflow-x-auto py-4">{awards.map((year) => <div key={year} className="min-w-40 border border-border bg-card p-6 text-center"><p className="font-display text-5xl text-bronze">{year}</p><p className="mt-3 text-xs uppercase tracking-[0.2em] text-muted-foreground">Parade of Homes</p></div>)}</div>; }
export function TestimonialCarousel() { const [i, setI] = useState(0); useEffect(() => { const id = window.setInterval(() => setI((v) => (v + 1) % testimonials.length), 5200); return () => clearInterval(id); }, []); const t = testimonials[i]; return <div className="border-y border-border py-12"><div className="mb-6 flex gap-1 text-bronze">{Array.from({ length: 5 }).map((_, n) => <Star key={n} size={18} fill="currentColor" />)}</div><AnimatePresence mode="wait"><motion.blockquote key={t.quote} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -20 }} className="max-w-4xl font-display text-4xl leading-tight md:text-6xl">“{t.quote}”</motion.blockquote></AnimatePresence><p className="mt-7 text-xs uppercase tracking-[0.24em] text-bronze">{t.name}</p></div>; }
export function BlogCard({ post }: { post: typeof blogPosts[number] }) { return <article className="group border border-border bg-card"><div className="h-72 overflow-hidden"><img src={post.image} alt={post.title} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="p-6"><p className="text-xs uppercase tracking-[0.22em] text-bronze">{post.category} / {post.date}</p><h3 className="mt-4 font-display text-3xl">{post.title}</h3><p className="mt-4 text-muted-foreground">{post.excerpt}</p><span className="nav-underline mt-6 inline-block text-xs uppercase tracking-[0.2em] text-bronze">Read More</span></div></article>; }

const quoteSchema = z.object({ name: z.string().trim().min(2, "Enter your full name"), email: z.string().trim().email("Enter a valid email"), phone: z.string().trim().min(7, "Enter a phone number"), service: z.string().optional(), projectType: z.string().optional(), referral: z.string().optional(), message: z.string().trim().min(10, "Tell us a little more about your project") });
type QuoteFields = z.infer<typeof quoteSchema>;
export function QuoteForm() { const [status, setStatus] = useState<"idle" | "success" | "error">("idle"); const submitContactFn = useServerFn(submitContact); const { register, handleSubmit, formState: { errors, isSubmitting }, reset } = useForm<QuoteFields>({ resolver: zodResolver(quoteSchema) }); const onSubmit = async (data: QuoteFields) => { setStatus("idle"); try { await submitContactFn({ data }); setStatus("success"); reset(); } catch { setStatus("error"); } }; const input = "w-full border border-border bg-background px-4 py-3 text-foreground outline-none transition focus:border-bronze focus:ring-1 focus:ring-bronze"; return <form onSubmit={handleSubmit(onSubmit)} className="grid gap-4"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm">Full Name<input className={input} {...register("name")} /></label><label className="text-sm">Email Address<input className={input} {...register("email")} /></label><label className="text-sm">Phone Number<input className={input} {...register("phone")} /></label><label className="text-sm">Service Interest<select className={input} {...register("service")}><option>Granite Countertops</option><option>Marble Countertops</option><option>Quartz Countertops</option><option>Quartzite Countertops</option><option>Custom Cabinets</option></select></label><label className="text-sm">Project Type<input className={input} {...register("projectType")} placeholder="Kitchen, bath, fireplace..." /></label><label className="text-sm">How Did You Hear About Us?<input className={input} {...register("referral")} /></label></div><label className="text-sm">Tell Us About Your Project<textarea className={`${input} min-h-36`} {...register("message")} /></label><label className="text-sm">Inspiration Photos<input type="file" className={input} /></label><div className="text-sm text-destructive">{Object.values(errors)[0]?.message}</div>{status === "success" && <p className="border border-bronze/40 bg-bronze/10 p-4 text-sm text-bronze">Thank you — your request was received. Our team will follow up shortly.</p>}{status === "error" && <p className="border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">Something went wrong. Please call {contact.phone}.</p>}<Button disabled={isSubmitting} variant="bronze" type="submit">{isSubmitting ? "Sending..." : "Submit Request"}</Button></form>; }

export function Footer() { return <footer className="bg-obsidian px-5 py-16 text-ivory md:px-10"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[1fr_.7fr_.7fr]"><div><AnimatedLogo /><p className="mt-6 max-w-md text-ivory/65">Premium stone countertops, backsplashes, vanity tops, fireplaces, sinks, and custom fabrication for refined spaces across {contact.serviceArea}.</p></div><div><h3 className="mb-5 text-xs uppercase tracking-[0.25em] text-bronze">Contact</h3><div className="space-y-3 text-ivory/70"><p>{contact.phone}</p><p>{contact.email}</p><p>{contact.address}</p></div></div><div><h3 className="mb-5 text-xs uppercase tracking-[0.25em] text-bronze">Quick Links</h3><div className="grid grid-cols-2 gap-3 text-sm text-ivory/70">{nav.map((n) => <Link key={n.to} to={n.to as never} className="hover:text-bronze">{n.label}</Link>)}<Link to="/privacy-policy" className="hover:text-bronze">Privacy Policy</Link></div></div></div><div className="mx-auto mt-12 flex max-w-7xl justify-between border-t border-ivory/10 pt-6 text-xs uppercase tracking-[0.18em] text-ivory/45"><p>© {new Date().getFullYear()} Creative Granite & Design</p><a href={externalLinks.instagram} target="_blank" rel="noreferrer">Instagram</a></div></footer>; }

export function StatsStrip() { const stats = ["Awarded for Best Custom Countertop", "20+ Years Experience", "Leader in Granite, Marble, and Quartz Fabrication", "Free Estimate", "3D Kitchen Visualizer"]; return <section className="bg-card px-5 py-8 md:px-10"><div className="mx-auto grid max-w-7xl gap-3 md:grid-cols-5">{stats.map((s) => <div key={s} className="border border-border p-5 text-center text-xs uppercase tracking-[0.18em] text-muted-foreground"><Check className="mx-auto mb-3 size-5 text-bronze" />{s}</div>)}</div></section>; }

export function JsonLd() { const data = useMemo(() => ({ "@context": "https://schema.org", "@type": "HomeAndConstructionBusiness", name: logoText, telephone: contact.phone, email: contact.email, address: { "@type": "PostalAddress", streetAddress: "1998 N. Redwood Rd.", addressLocality: "Salt Lake City", addressRegion: "UT", postalCode: "84116" }, areaServed: ["Utah", "Idaho", "Wyoming"], makesOffer: services.slice(0, 9).map((s) => ({ "@type": "Offer", itemOffered: s.title })) }), []); return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }} />; }
